# Generated by Django 4.2.1 on 2023-06-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0009_notincludeservices_includeservices"),
    ]

    operations = [
        migrations.AddField(
            model_name="services",
            name="image",
            field=models.ImageField(
                default="services_images/services.png", upload_to="services_images"
            ),
        ),
    ]
