# Generated by Django 4.2.1 on 2023-07-19 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("services", "0007_alter_services_managers_remove_services_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_status",
                    models.CharField(
                        choices=[
                            ("قيد المراجعة", "قيد المراجعة"),
                            ("قيد التنفيذ", "قيد التنفيذ"),
                            ("مكتمل", "مكتمل"),
                            ("مرفوض", "مرفوض"),
                        ],
                        default="قيد المراجعة",
                        max_length=12,
                    ),
                ),
                ("delivery_date", models.DateField()),
                ("delivery_time", models.TimeField()),
                ("order_create", models.DateTimeField(auto_now_add=True)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="services.services",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.location",
                    ),
                ),
            ],
        ),
    ]
