# Generated by Django 4.2.1 on 2023-07-11 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_customorder"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customorder",
            old_name="created_by",
            new_name="create_by",
        ),
    ]
