# Generated by Django 4.2.1 on 2023-07-20 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_review"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descriptions", models.TextField()),
                ("status", models.CharField(blank=True, null=True)),
                ("icons", models.ImageField(upload_to="")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracks_list",
                        to="orders.order",
                    ),
                ),
            ],
        ),
    ]
