# Generated by Django 4.2.1 on 2023-07-20 07:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="tracking",
            name="create_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
