# Generated by Django 4.2.1 on 2023-07-14 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="custom_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="orders.customorder",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="orders.order",
            ),
        ),
    ]
