# Generated by Django 4.2.1 on 2023-07-15 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_location_address_name"),
        ("orders", "0007_notification_custom_order_alter_notification_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="customorder",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.location",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.location",
            ),
        ),
    ]
