# Generated by Django 4.2.1 on 2023-07-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="services",
            old_name="created_by",
            new_name="user",
        ),
        migrations.AddField(
            model_name="services",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="services",
            name="price_from",
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name="services",
            name="price_to",
            field=models.PositiveIntegerField(default=250),
        ),
    ]
