# Generated by Django 4.2.1 on 2023-07-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_alter_services_name_alter_services_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="services",
            name="status",
            field=models.CharField(
                choices=[("fixed", "fixed"), ("custom", "custom")],
                default="custom",
                max_length=10,
            ),
        ),
    ]
