# Generated by Django 4.2.1 on 2023-07-17 16:26

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0005_services_status"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="services",
            managers=[
                ("quest", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name="services",
            name="image",
            field=models.ImageField(
                blank=True,
                default="services_images/services.png",
                null=True,
                upload_to="services_images",
            ),
        ),
        migrations.AlterField(
            model_name="services",
            name="slug",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
