# Generated by Django 4.2.1 on 2023-08-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_services_managers_remove_services_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='name_en',
        ),
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
