# Generated by Django 4.2.1 on 2023-05-24 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0007_services_name_en_alter_services_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="services",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="services",
                to="services.category",
            ),
        ),
    ]
