# Generated by Django 4.2.1 on 2023-07-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0010_services_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.ImageField(blank=True, null=True, upload_to="category_icons"),
        ),
    ]
