# Generated by Django 4.2.1 on 2023-07-05 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0012_customservices"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomServices",
        ),
    ]
