# Generated by Django 4.2.1 on 2023-06-29 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(default="فلسطين", max_length=100)),
                ("city", models.CharField(help_text="المدينة", max_length=100)),
                ("building", models.CharField(help_text="البناية", max_length=100)),
                (
                    "apartment_number",
                    models.CharField(help_text="رقم الشقة", max_length=20),
                ),
                (
                    "phone_number",
                    models.CharField(help_text="رقم الهاتف", max_length=20),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
