# Generated by Django 4.2.1 on 2023-07-19 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ServiceProvider",
        ),
    ]
