# Generated by Django 4.2.1 on 2023-06-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="صورة شخصية",
                null=True,
                upload_to="profile_images",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(
                blank=True, help_text="رقم الهاتف", max_length=20, null=True
            ),
        ),
    ]
