# Generated by Django 4.2.1 on 2023-07-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customservices_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="customservices",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
