# Generated by Django 4.2.1 on 2023-07-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_serviceprovider_customservices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customservices",
            name="name",
            field=models.CharField(max_length=250),
        ),
    ]
