# Generated by Django 4.2.1 on 2023-07-05 07:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_customservices_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customservices",
            name="descriptions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customservices",
            name="request_date",
            field=models.DateField(
                default=datetime.datetime(2023, 7, 5, 10, 17, 31, 93721)
            ),
        ),
    ]
