# Generated by Django 4.2.1 on 2023-07-05 07:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_customservices_descriptions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customservices",
            name="request_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
