# Generated by Django 4.2.1 on 2023-07-20 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CodeActivate",
        ),
    ]
